### ISSUE TITLE
infinite scroll

### ISSUE THREAD

**Issue by bamaarintoko** [sonaye/react-native-collapsible-header#12]
how to make infinite scroll like FlatList?

**Comment by sonaye** [comment]
Take a look at #3.

**Comment by bamaarintoko** [comment]
I've seen, but still can not solve my problem, does this library support infinite scroll?

**Comment by sonaye** [comment]
There is a solution for working with `FlatList` in https://github.com/sonaye/react-native-collapsible-header/issues/3#issuecomment-315658554, did you try it?

**Comment by bamaarintoko** [comment]
i try FlatList for renderContent, but still can't solve my problem :/

**Comment by sonaye** [comment]
Try the solution offered in the link I just posted, let me know if that solves your issue.

**Comment by sonaye** [comment]
You can now use FlatList out of the box in `0.0.13`
