### ISSUE TITLE
Lag when scrolling

### ISSUE THREAD

**Issue by gilbertKaradja** [sonaye/react-native-collapsible-header#13]
I really wanted this solution to work. Its simple and straightforward but unfortunately the animation of theheader lags quite noticeably.  For those that experienced the same issue I would recommend looking at  https://github.com/janicduplessis/react-native-scrollable-header

**Comment by sonaye** [comment]
Please take the time to detail the issue you are facing next time, explain how it is lagging, compare  what are you expecting vs. what you are seeing, offer a piece of code to reproduce, etc .. help me help you.

I just released a new version, kindly test it and provide me with some feedback.

**Comment by gilbertKaradja** [comment]
Sorry for not providing enough information.  I wan't really sure what was causing the issue before. The issue was not using the native driver to run the animation which I see you added in subsequent commits. Nice work. Also you should add a zIndex to the header since most users would like to be able to click some navigation controls and currently the ScrollView overlays the header

**Comment by gilbertKaradja** [comment]
Pls correct me if I'm wrong about the above since I didnt have a chance to test your latest built. Thanks

**Comment by sonaye** [comment]
Yep when I worked on this package last year we didn't have access to the native driver at that time, it's been a while. The header does actually have a higher zIndex now and also before. I did some testing with some buttons however and  I did find a bug that I introduced yesterday, it's fixed now.

```javascript
<Foo />
<Bar /> // has a higher zIndex than Foo (just by placing it after Foo)
<Baz /> // has a higher zIndex than Foo & Bar
```
