### ISSUE TITLE
Circular or curved at bottom

### ISSUE THREAD

**Issue by AbhishekDS-Userfacet** [sonaye/react-native-collapsible-header#14]
How to achieve a curved shape at the bottom instead of rectangular (Design as shown in image)?
![circular toolbar](https://user-images.githubusercontent.com/37110839/40641962-2786d71c-6339-11e8-969b-e8c9f1b62eca.png)

**Comment by sonaye** [comment]
The header can be of any view type, see https://stackoverflow.com/questions/46244995/curved-bottom-on-view.
