### ISSUE TITLE
Support refs binding

### ISSUE THREAD

**Issue by ddcrobert** [sonaye/react-native-collapsible-header#17]
Hi, before using this library, I was able to control the scroll of my FlatList via the following lines
using the following magic string
`const REF_LIST = "whatever";`
on the flatlist component
`<FlatList ref={REF_LIST} ...>`
then I could offset the scroll
`this.refs[REF_LIST].scrollToOffset({ x: 0, y: whateverY, animated: true });`

I guess embedding the component behind an AnimatedComponent is what breaks this ref. Any idea how to workaround / fix this ?
My use case btw, I need to be able to scroll programmatically to the top but also to whatever y within the flatlist.

**Comment by sonaye** [comment]
You can access the ref in an animated component using:

```js
this.refs[REF_LIST]._component.scrollToOffset()
```

It's recommended to use the new refs API, the one you are using has been depreciated for a while:

```js
REF_LIST = React.createRef() // class prop
<Foo ref={REF_LIST} />
this.REF_LIST.current._component.scrollToOffset()
```

This package doesn't give you direct access to the inner ref of the scrollView component yet, I will address that in a next release. You can just grab the component code temporarily and modify it to fit your use case.
