### ISSUE TITLE
Can we fix a certain part of the header ?

### ISSUE THREAD

**Issue by PeteOyable** [sonaye/react-native-collapsible-header#7]
Hi there,

I'm using your package on a app and it works great. I need to fix a certain element and I don't know if I should render this element as the header or the content.

If I render it into the header, it fades with it, but if I render it into the content, there is no way for me tox fix it. Do you see any way I could solve this ?

**Comment by sonaye** [comment]
Hey! could you clarify more on the exact behavior you are looking for? no change in opacity when scrolling, that's all?

**Comment by PeteOyable** [comment]
Thank you for answering so fast.

I took a look at the source code, I'll change it a little bit to fit my case. I think it's a particular case.
I'll let you know and show you the rendering once it's done.

**Comment by sonaye** [comment]
Sounds good, we can still evaluate and look into adding support for your case within the package out of the box too.
