### ISSUE TITLE
Dynamic max height

### ISSUE THREAD

**Issue by csuermann** [sonaye/react-native-collapsible-header#8]
This is such a nice component! Thank you for the good work! One nice enhancement would be, if the max height could be calculated dynamically based on the contents of the header.

**Comment by sonaye** [comment]
Hey! I don't think that this would be possible due to how Animated works, we need to define the limits and send them to the native side before any rendering. https://github.com/sonaye/react-native-collapsible-header/commit/e42746793315ce758d84f71e8742c57c95679c47#L24-L27

Do you have any suggestions on how to achieve this?

**Comment by csuermann** [comment]
Ah, I see. I haven't really looked into it yet, but could it be possible to update the interpolation via onLayout()?

**Comment by sonaye** [comment]
I think that could work, still not sure about adding it to the package though, can I ask what is your specific use case?

**Comment by sonaye** [comment]
Try something like this, not sure if it's going to work, let me know.
```javascript
<Collapsible
  backgroundColor="yellow"
  ref={ref => (this.collapsible = ref)}
  renderContent={<View style={{ height: 1000 }} />}
  renderHeader={
    <View
      onLayout={e => {
        const max = e.nativeEvent.layout.height;
        this.collapsible.height = this.collapsible.scroll.interpolate({
          inputRange: [-max, 0, max],
          outputRange: [max * 2, max, max]
        });
      }}
      style={{ height: 250 }}
    />
  }
/>
```

**Comment by sonaye** [comment]
Try these too, from the top of my head.
```javascript
<Collapsible
  backgroundColor="yellow"
  ref={ref => (this.collapsible = ref)}
  renderContent={<View style={{ height: 1000 }} />}
  renderHeader={
    <View
      onLayout={e => this.collapsible.setNativeProps({ max: e.nativeEvent.layout.height })}
      style={{ height: 250 }}
    />
  }
/>
```

```javascript
export default class extends Component {
  state = { max: null };

  render() {
    return (
      <Collapsible
        backgroundColor="yellow"
        max={this.state.max}
        renderContent={<View style={{ height: 1000 }} />}
        renderHeader={
          <View
            onLayout={e => this.setState({ max: e.nativeEvent.layout.height })}
            style={{ height: 250 }}
          />
        }
      />
    );
  }
}
