### ISSUE TITLE
Swiping on header doesn't scroll up

### ISSUE THREAD

**Issue by wootwoot1234** [sonaye/react-native-collapsible-header#9]
Thanks for building this.  I was really happy when I found it.

Is it possible to make the content scroll when you swipe on the header.  I'm using the collapsible header with an image so the header is very large.  Not being able to swipe up on the image makes the app feel broken.

**Comment by sonaye** [comment]
Hey! Yes this is one of the downsides at the moment, which is why I opened #4, I plan to address this shortly. I already have something figured out just need to test some edge cases before releasing it.

<img src="https://user-images.githubusercontent.com/23000873/30402750-8a0af0b6-98e7-11e7-87be-4813ed15586e.gif" width="400">

**Comment by wootwoot1234** [comment]
That looks awesome!! Do you know when it will be released.  I would love to use it. Thanks!

**Comment by sonaye** [comment]
It's failing tests for other cases that were supported before this patch, I can't release it without having them pass first to avoid any breaking changes. I can't give you an exact timeline but I am actively working on this -I use it in production- and as soon as it's ready it will be out.

**Comment by sonaye** [comment]
If you are interested in the diff that made the gif above possible, here it is:

<img width="636" alt="screen shot 2017-09-14 at 1 27 25 pm" src="https://user-images.githubusercontent.com/23000873/30425074-a35f1696-9950-11e7-9c9f-0968ed243fce.png">

- Change the order of the views to reflect modifications on their z indices
- Add a style marginTop prop

**Comment by sonaye** [comment]
Closing in favor of #4.
